// GENERATED by `npm run fetch:logos` — do not edit by hand.
//
// Domains whose logo is stored in public/logos/ and therefore served from this
// app's own origin. A local file beats any provider: no third-party request at
// render time, nothing to rate-limit, nothing that can start returning a globe
// or disappear, and the file is cached by whatever already serves the site.
//
// Empty is a valid state — every domain then falls back to the configured
// provider if there is one, and to the monogram if there isn't. It ships empty
// because the logos are somebody else's artwork fetched from their own site:
// that fetch belongs to whoever deploys this, not to the repo.

export const LOCAL_LOGOS: Record<string, string> = {};
