// Fallback fixture — used only when both live sources are unreachable at
// request time (ingest.ts). Real-shaped rows profiled from the live feed, with
// date_posted values expressed as offsets from load time so the decay rail
// demonstrates every age bucket. Rows with `terms` read as internships.

import type { RawListing } from './types';

const now = Math.floor(Date.now() / 1000);
const H = 3600;
const D = 86400;

export const SAMPLE_LISTINGS: RawListing[] = [
  {
    source: 'Simplify',
    category: 'Software',
    company_name: 'Jane Street',
    id: 'sample-0001',
    title: 'Software Engineering Internship',
    active: true,
    terms: ['Summer 2026'],
    date_updated: now - 2 * H,
    date_posted: now - 2 * H,
    url: 'https://job-boards.greenhouse.io/janestreet/jobs/4512?gh_jid=4512',
    locations: ['NYC'],
    company_url: 'https://simplify.jobs/c/JaneStreet',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'AI/ML/Data',
    company_name: 'SpaceX',
    id: 'sample-0002',
    title: 'Machine Learning Intern (Autonomy)',
    active: true,
    terms: ['Summer 2026', 'Fall 2026'],
    date_updated: now - 9 * H,
    date_posted: now - 9 * H,
    url: 'https://boards.greenhouse.io/spacex/jobs/7781',
    locations: ['Hawthorne, CA', 'Redmond, WA', 'Bastrop, TX'],
    company_url: 'https://simplify.jobs/c/SpaceX',
    is_visible: true,
    sponsorship: 'Other',
    degrees: ["Bachelor's"],
  },
  {
    source: 'Simplify',
    category: 'Quantitative Finance',
    company_name: 'IMC Trading',
    id: 'sample-0003',
    title: 'Quantitative Trader Intern',
    active: true,
    terms: ['Summer 2026'],
    date_updated: now - 2 * D,
    date_posted: now - 2 * D,
    url: 'https://jobs.lever.co/imc/abc-123',
    locations: ['Chicago, IL'],
    company_url: 'https://simplify.jobs/c/IMC',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'Hardware Engineering',
    company_name: 'Tesla',
    id: 'sample-0004',
    title: 'Firmware Engineering Intern, Powertrain',
    active: true,
    terms: ['Spring 2026'],
    date_updated: now - 5 * D,
    date_posted: now - 5 * D,
    url: 'https://www.tesla.com/careers/search/job/12345',
    locations: ['Palo Alto, CA', 'Austin, TX'],
    company_url: 'https://simplify.jobs/c/Tesla',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'Product Management',
    company_name: 'Ramp',
    id: 'sample-0005',
    title: 'Product Management Intern',
    active: true,
    terms: ['Summer 2026'],
    date_updated: now - 12 * D,
    date_posted: now - 12 * D,
    url: 'https://jobs.ashbyhq.com/ramp/def-456',
    locations: ['NYC', 'Remote in USA'],
    company_url: 'https://simplify.jobs/c/Ramp',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'Software',
    company_name: 'Innodata',
    id: 'sample-0006',
    title: 'Software Engineer, New Grad',
    active: true,
    date_updated: now - 30 * H,
    date_posted: now - 30 * H,
    url: 'https://job-boards.greenhouse.io/innodatainc/jobs/9001',
    locations: ['Remote in USA'],
    company_url: 'https://simplify.jobs/c/Innodata',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'AI/ML/Data',
    company_name: 'Palantir',
    id: 'sample-0007',
    title: 'Forward Deployed Software Engineer',
    active: true,
    date_updated: now - 4 * H,
    date_posted: now - 4 * H,
    url: 'https://jobs.lever.co/palantir/xyz-789',
    locations: ['Seattle, WA', 'Denver, CO', 'Washington, DC', 'NYC', 'Palo Alto, CA'],
    company_url: 'https://simplify.jobs/c/Palantir',
    is_visible: true,
    sponsorship: 'Other',
    degrees: ["Bachelor's"],
  },
  {
    source: 'Simplify',
    category: 'Hardware',
    company_name: 'Rivian',
    id: 'sample-0008',
    title: 'Electrical Engineer, New Grad Rotation',
    active: true,
    date_updated: now - 6 * D,
    date_posted: now - 6 * D,
    url: 'https://jobs.ashbyhq.com/rivianvw.tech/ghi-012',
    locations: ['Irvine, CA'],
    company_url: 'https://simplify.jobs/c/Rivian',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'Software',
    company_name: 'DRW',
    id: 'sample-0009',
    title: 'Software Developer Intern',
    active: true,
    terms: ['Summer 2027'],
    date_updated: now - 20 * H,
    date_posted: now - 20 * H,
    url: 'https://job-boards.greenhouse.io/drweng/jobs/3300',
    locations: ['Chicago, IL', 'London, UK'],
    company_url: 'https://simplify.jobs/c/DRW',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'AI/ML/Data',
    company_name: 'Five Rings',
    id: 'sample-0010',
    title: 'Data Engineer',
    active: true,
    date_updated: now - 15 * D,
    date_posted: now - 15 * D,
    url: 'https://job-boards.greenhouse.io/fiveringsllc/jobs/2200',
    locations: ['NYC'],
    company_url: 'https://simplify.jobs/c/FiveRings',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'Software',
    company_name: 'Stripe',
    id: 'sample-0011',
    title: 'Software Engineer Intern',
    active: true,
    terms: ['Fall 2026'],
    date_updated: now - 40 * H,
    date_posted: now - 40 * H,
    url: 'https://stripe.com/jobs/listing/software-engineer-intern/1111?utm_source=x',
    locations: ['Seattle, WA'],
    company_url: 'https://simplify.jobs/c/Stripe',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
  {
    source: 'Simplify',
    category: 'Quant',
    company_name: 'Citadel',
    id: 'sample-0012',
    title: 'Quantitative Research Analyst',
    active: true,
    date_updated: now - 1 * H,
    date_posted: now - 1 * H,
    url: 'https://www.citadel.com/careers/details/quant-research-analyst-2222/',
    locations: ['NYC', 'Chicago, IL'],
    company_url: 'https://simplify.jobs/c/Citadel',
    is_visible: true,
    sponsorship: 'Other',
    degrees: [],
  },
];
